[theme]
primaryColor = "#00FF6A"
backgroundColor = "#060270"
secondaryBackgroundColor = "#1C1F26"
textColor = "#5DE2E7"


[server]
headless = true
port = 8501
enableCORS = false

[client]
toolbarMode = "minimal"
